Repository CorvusOps/PMMS, pull requests merged in 2022-11, with the labels that each got.

#1 Tailwind setup & Initial login
  .gitignore
  images/Text.png
  images/city-background.jpeg
  index.html
  package-lock.json
  package.json
  public/output.css
  src/input.css
  tailwind.config.js
Labels: good first issue

#3 Add initial Sql Schema
  sql/pmms.sql
Labels: good first issue

#6 Updated README to accomodate deliverables documentation
  README.md
Labels: enhancement

#7 Add Initial Includes
  src/includes/connectdb.php
  src/includes/error.php
  src/includes/logout.php
Labels: enhancement, good first issue

#9 city html pages to php and city sidebar
  src/city/cityBarangays.html
  src/city/cityBarangays.php
  src/city/cityCMRecords.html
  src/city/cityCMRecords.php
  src/city/cityDashboard.html
  src/city/cityDashboard.php
  src/city/cityFTRecords.html
  src/city/cityFTRecords.php
  src/city/cityITRecords.html
  src/city/cityITRecords.php
  src/city/cityRecords.php
  src/city/cityUNRecords.html
  src/city/cityUNRecords.php
  src/includes/citySidebar.php
Labels: enhancement

#10 Add Login Authentication
  index.html
  package-lock.json
  package.json
  public/output.css
  src/includes/authentication.php
Labels: good first issue

#11 Update .gitignore
  .gitignore
Labels: enhancement

#12 Update Several Includes
  src/includes/adminSidebar.php
  src/includes/citySidebar.php
  src/includes/connectdb.php
  src/includes/logout.php
Labels: enhancement

#13 Add a create account template
  src/admin/adminAccounts.php
  src/admin/modalAddAccountTemplate.php
Labels: enhancement

#14 Appended barangay pages
  src/barangay/barangayCMRecords.php
  src/barangay/barangayDashboard.php
  src/barangay/barangayFTRecords.php
  src/barangay/barangayITRecords.php
  src/barangay/barangayRecords.php
  src/barangay/barangayUNRecords.php
  src/includes/barangaySidebar.php
Labels: good first issue

#15 Update README.md
  README.md
Labels: enhancement

#23 General Update for Include files
  src/includes/authentication.php
  src/includes/barangaySidebar.php
  src/includes/citySidebar.php
  src/includes/connectdb.php
  src/includes/error404.php
  src/includes/errors.php
Labels: enhancement

#24 Update and Hotfix Index and add account
  index.php
  sql/pmms.sql
  src/crud/tbusersAddAccount.php
Labels: enhancement
